#!/bin/sh
# prerm script for keymagic3
#
# This script is executed before the package is removed

set -e

case "$1" in
    remove|upgrade|deconfigure)
        # Notify about IBus
        if [ -f /usr/share/ibus/component/keymagic3.xml ]; then
            echo "KeyMagic 3 IBus component will be removed."
            echo "If KeyMagic 3 is currently active, please switch to another input method."
        fi
        ;;

    failed-upgrade)
        ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

exit 0