# KeyMagic Package Metadata
# This file contains metadata for various package formats

[common]
name = "keymagic3"
version = "0.0.1"
description = "KeyMagic 3 - A smart keyboard input method for Myanmar and other languages"
long_description = """
KeyMagic 3 is a powerful and flexible input method that allows users to type
in Myanmar and other complex scripts using standard keyboards. It features:

- Smart keyboard layout system with .km2 format
- Real-time script conversion and transliteration
- Support for multiple languages and scripts
- Graphical configuration interface
- IBus integration for Linux systems
"""
homepage = "https://github.com/thantthet/keymagic-3"
repository = "https://github.com/thantthet/keymagic-3"
license = "GPL-3.0"
copyright = "2025, Thant Thet Khin Zaw and contributors"
maintainer = "Thant Thet Khin Zaw <contact@keymagic.net>"
categories = ["Utility", "System", "InputMethod"]
keywords = ["keyboard", "input-method", "myanmar", "burmese", "ibus"]

[debian]
section = "utils"
priority = "optional"
architecture = ["amd64", "arm64", "armhf"]
depends = [
    "libc6 (>= 2.31)",
    "libgcc-s1 (>= 10)",
    "libgtk-3-0 (>= 3.24)",
    "libcairo2 (>= 1.16)",
    "libpango-1.0-0 (>= 1.44)",
    "libglib2.0-0 (>= 2.64)",
    "ibus (>= 1.5.0)"
]
recommends = [
    "fonts-myanmar"
]
suggests = [
    "ibus-table"
]

[rpm]
group = "User Interface/X"
vendor = "KeyMagic Project"
packager = "Thant Thet Khin Zaw <contact@keymagic.net>"
requires = [
    "glibc >= 2.31",
    "gtk3 >= 3.24",
    "cairo >= 1.16",
    "pango >= 1.44",
    "glib2 >= 2.64",
    "ibus >= 1.5.0"
]
build_requires = [
    "rust >= 1.70",
    "cargo",
    "gcc",
    "make",
    "pkg-config",
    "gtk3-devel",
    "cairo-devel",
    "pango-devel",
    "glib2-devel",
    "ibus-devel"
]

[appimage]
desktop_file = "keymagic.desktop"
icon = "keymagic.png"
categories = "Utility;System;"
terminal = false

[snap]
grade = "stable"
confinement = "strict"
base = "core22"
slots = [
    "ibus-keymagic"
]
plugs = [
    "desktop",
    "desktop-legacy",
    "wayland",
    "x11",
    "home",
    "removable-media",
    "ibus"
]

[flatpak]
runtime = "org.gnome.Platform"
runtime_version = "45"
sdk = "org.gnome.Sdk"
command = "keymagic-gui"
finish_args = [
    "--share=ipc",
    "--socket=fallback-x11",
    "--socket=wayland",
    "--filesystem=home",
    "--talk-name=org.freedesktop.IBus"
]