name: Test Windows SignPath Build

on:
  push:
    branches:
      - feature/signpath-integration
    paths:
      - '.github/workflows/build-windows-signed.yml'
      - '.github/workflows/test-windows-signpath.yml'
      - 'keymagic-windows/**'
      - 'keymagic-core/**'
      - 'keymagic-gui/**'
  pull_request:
    branches:
      - master
    paths:
      - '.github/workflows/build-windows-signed.yml'
      - 'keymagic-windows/**'
      - 'keymagic-core/**'
      - 'keymagic-gui/**'

jobs:
  # Test with dual signing (binaries + installer)
  test-build-dual-signed:
    name: Test Windows Build (Dual Signed)
    uses: ./.github/workflows/build-windows-dual-signed.yml
    with:
      version: '0.0.1-test-dual-signed'
      sign: true
    secrets: inherit

  verify-artifacts:
    name: Verify Build Artifacts
    needs: test-build-dual-signed
    runs-on: ubuntu-latest
    
    steps:
      - name: Download installer artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-installer
          path: ./installer/
      
      - name: List downloaded artifacts
        run: |
          echo "=== Downloaded Artifacts ==="
          ls -la ./installer/
          echo ""
          echo "=== File Details ==="
          file ./installer/KeyMagic3-Setup-*.exe || true
          echo ""
          echo "=== File Size ==="
          du -h ./installer/KeyMagic3-Setup-*.exe || true
      
      - name: Check build status
        run: |
          echo "=== Build Status ==="
          echo "Dual-signed build: ${{ needs.test-build-dual-signed.result }}"
          echo ""
          echo "Note: Signature verification requires Windows environment."
          echo "Verify on Windows using:"
          echo "  # Check installer signature"
          echo "  Get-AuthenticodeSignature 'KeyMagic3-Setup-0.0.1-test-dual-signed.exe'"
          echo ""
          echo "  # Extract and check binary signatures"
          echo "  # After installation, check individual binaries:"
          echo "  Get-AuthenticodeSignature 'C:\Program Files\KeyMagic\keymagic-gui.exe'"
          echo "  Get-AuthenticodeSignature 'C:\Program Files\KeyMagic\KeyMagicTSF_x64.dll'"
      
      - name: Upload test results summary
        run: |
          cat > test-summary.md << EOF
          # Windows Build Test Summary
          
          ## Build Configuration
          - **Dual-Signed Build**: 0.0.1-test-dual-signed (Status: ${{ needs.test-build-dual-signed.result }})
          - **Signing**: Dual-signing enabled (binaries + installer)
          - **Workflow Run**: [#${{ github.run_number }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
          
          ## Artifacts
          - Signed Installer: KeyMagic3-Setup-0.0.1-test-dual-signed.exe
          - Contains individually signed: EXEs (keymagic-gui, keymagic-tray) and DLLs (KeyMagicTSF)
          
          ## Next Steps
          1. Download the installer from the workflow artifacts
          2. Test installation on Windows (x64 and ARM64 if possible)
          3. Verify signatures with PowerShell:
             \`\`\`powershell
             # Check installer signature (should show "Valid")
             Get-AuthenticodeSignature "KeyMagic3-Setup-0.0.1-test-dual-signed.exe"
             
             # After installation, check individual binary signatures
             Get-AuthenticodeSignature "C:\Program Files\KeyMagic\keymagic-gui.exe"
             Get-AuthenticodeSignature "C:\Program Files\KeyMagic\KeyMagicTSF_x64.dll"
             \`\`\`
          
          ## SignPath Dashboard
          If signing was enabled, check the SignPath dashboard for:
          - Signing request status
          - Certificate details
          - Any policy violations or warnings
          EOF
          
          cat test-summary.md
      
      - name: Save test summary
        uses: actions/upload-artifact@v4
        with:
          name: test-summary
          path: test-summary.md